In [1]:
import torch

In [2]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones([3,4,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [7]:
x = torch.Tensor([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

In [8]:
x.size()

torch.Size([3, 4])

In [9]:
x.shape

torch.Size([3, 4])

In [10]:
x[0]

tensor([1., 2., 3., 4.])

In [11]:
x[1]

tensor([5., 6., 7., 8.])

In [12]:
x[0,0]

tensor(1.)

In [13]:
x[:,0]

tensor([1., 5., 9.])

In [14]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [15]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [16]:
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [17]:
x+y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [18]:
x*y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [19]:
x/y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [20]:
x%y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

Какая операция с тензорами a, b
```
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])
```
позволяет получить следующий вывод?
```
tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
```

In [21]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

In [23]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
b

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])

In [22]:
a % b

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
a.shape

torch.Size([5, 4])

In [26]:
b[0] + a[2]

tensor([2., 3., 4., 5.])

In [27]:
a + b

tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])

### ***
Какая операция с тензорами a, b:
```
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20]])
```
позволяет получить следующий вывод?
```
tensor([2., 3., 4., 5.])
```

In [30]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20]])

In [29]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
b

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])

In [32]:
b[0] + a[2]

tensor([2., 3., 4., 5.])

In [33]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [34]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [35]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [36]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [38]:
mask = x > 3

In [39]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

#### ***

Реализуйте при помощи pyTorch функцию, которая возвращает сумму (x.sum()) элементов тензора X, строго превышающих значение limit, которое является входным значением алгоритма.

Входная матрица: 
```
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

In [40]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = X[X>limit].sum()

print(larger_than_limit_sum)

1
tensor(44)


#### ***
Что будет в переменной x в результате выполнения следующего кода?

In [41]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = x
y[2] = torch.ones(3)

In [42]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 1, 1]])

In [43]:
x.dtype

torch.int64

In [44]:
x = x.double()
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 1., 1.]], dtype=torch.float64)


In [45]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])

In [46]:
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [47]:
x = torch.from_numpy(x)

In [48]:
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=torch.int32)

In [49]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [50]:
x = torch.rand([2000,3000])

In [51]:
x

tensor([[0.2952, 0.9549, 0.9198,  ..., 0.1068, 0.5318, 0.3047],
        [0.4414, 0.5088, 0.6574,  ..., 0.5853, 0.8864, 0.1989],
        [0.7452, 0.1051, 0.9128,  ..., 0.3341, 0.0219, 0.7702],
        ...,
        [0.7515, 0.4058, 0.1199,  ..., 0.8015, 0.2807, 0.9975],
        [0.4787, 0.5882, 0.6662,  ..., 0.3946, 0.0712, 0.8991],
        [0.7540, 0.3698, 0.9622,  ..., 0.2889, 0.3501, 0.9909]])

In [52]:
torch.cuda.is_available()

True

In [55]:
device = torch.device('cuda:0')

In [56]:
device

device(type='cuda', index=0)

In [57]:
x_cuda = x.to(device)

In [60]:
%time y = (x - x + x * 10.0) ** 2

Wall time: 120 ms


In [61]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

Wall time: 5 ms
